data:
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
  AzureWebJobsStorage: <BASE64 ENCODED CONNECTION STRING>
apiVersion: v1
kind: Secret
metadata:
  name: demo-keda
  namespace: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-keda
  namespace: demo
  labels:
    app: demo-keda
spec:
  selector:
    matchLabels:
      app: demo-keda
  template:
    metadata:
      labels:
        app: demo-keda
    spec:
      containers:
      - name: demo-keda
        image: <YOUR REGISTRY NAME>.azurecr.io/demo-keda:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: Demo
        envFrom:
        - secretRef:
            name: demo-keda
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-keda
  namespace: demo
spec:
  scaleTargetRef:
    name: demo-keda
  cooldownPeriod:  10 
  minReplicaCount: 0
  maxReplicaCount: 2
  advanced:                            
    restoreToOriginalReplicaCount: true
  triggers:
  - type: azure-queue
    metadata:
      connectionFromEnv: AzureWebJobsStorage
      queueName: myqueue-items
      queueLength: '1'

